export enum ERROR_CODES {
  ACCOUNT_EXIST_ERROR = 'ACCOUNT EXISTS',
  EMAIL_NOT_VERIFIED_LOGIN = 'EMAIL NOT VERIFIED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  USER_NOT_ADDED = 'USER NOT ADDED',
  EMAIL_NOT_VERIFIED_REGISTER = 'EMAIL_NOT_VERIFIED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  OTP_NOT_FOUND = 'OTP_NOT_FOUND',
  OTP_EXPIRED = 'OTP_EXPIRED',
  INCORRECT_OTP = 'INCORRECT_OTP',
  RESET_LINK_EXPIRED = 'RESET_LINK_EXPIRED',
}

export enum SUCCESS_CODES {
  ACCOUNT_CREATED = 'ACCOUNT CREATED',
  LOGGED_IN_SUCCESSFULLY = 'LOGGED_IN_SUCCESSFULLY',
  OK = 'OK',
  CREATED = 'CREATED',
  USER_VERIFIED = 'USER_VERIFIED',
}
